version: 2.1


jobs:
  run-api:
    docker:
      - image: circleci/node:15.4
    steps:
      - run:
          command: |
            curl --location --request POST 'http://f126c4922131.ngrok.io/pipeline/register' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "circleci-build-url": $CIRCLE_BUILD_URL
            }'

workflows:
  node-test-and-deploy:
    jobs:
      - run-api